title: Hello, world! I'm LIJUN CUI
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: LIJUN CUI # add your name
author-img: https://avatars.githubusercontent.com/u/86622407?s=400&u=e53567fca29d0edca8668220d64d36315091df05&v=4 # add your photo
about-author: I am a fitness personal trainer focusing on personal growth. Always open to discuss. 我是一个教练。 # add description
social-twitter: @Lijunpersonalt1 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: lijun.cui.cc@gmail.com # add your Email address

# Disqus
discus-identifier: Lijunpersonaltraining # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
